app:
  name: app
  image: sugesh23/springboot:latest
  replicaCount: 1

mysql:
  database: challenge

service:
  type: LoadBalancer
  port: 80

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

readinessProbe:
  path: /actuator/health
  port: 8080
  initialDelaySeconds: 10
  periodSeconds: 5

livenessProbe:
  path: /actuator/health
  port: 8080
  initialDelaySeconds: 15
  periodSeconds: 10

aws:
  region: us-west-2
  secretName: devops-challenge-secret
  secretProperty: mysql-root-password