app:
  image: sugesh23/devops-coding-challenge-app:latest
  replicaCount: 1
  service:
    type: LoadBalancer
    port: 8080
  env:
    SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/challenge?createDatabaseIfNotExist=true
    SPRING_DATASOURCE_WRITER_URL: jdbc:mysql://db:3306/challenge?createDatabaseIfNotExist=true
    SPRING_DATASOURCE_USERNAME: root
    SPRING_DATASOURCE_PASSWORD: dev

db:
  image: mysql:8.0
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3306
  env:
    MYSQL_ROOT_PASSWORD: dev  
    MYSQL_DATABASE: challenge
  storage:
    size: 5Gi

