apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: springboot-app
spec:                     
  selector:
    app: springboot-app
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer