apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.db.env.MYSQL_ROOT_PASSWORD | b64enc }}
  MYSQL_DATABASE: {{ .Values.db.env.MYSQL_DATABASE | b64enc }}
